# Generated by Django 5.2.7 on 2025-11-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avater',
            new_name='avatar',
        ),
    ]
