# Generated by Django 5.2.7 on 2025-11-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_avater_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='bio',
        ),
    ]
